### PR TITLE
Rewrite using got replacing deprecated request module

### PR DESCRIPTION
**Pull request by montdidier**
The [request module has been deprecated](https://github.com/request/request/issues/3142). This is an uplift preserving existing functionality using [got](https://github.com/sindresorhus/got).

NB: This branch requires node v10 or higher to work, which is probably not a huge issue since node is deprecated below v10 now. Just making it clear.

### CODE REVIEW

**Comment by thomasdavis** [comment]
Hey @montdidier, great work, would you just like to become a contributor with npm publish access? If so, just let me know your npm username

**Comment by montdidier** [comment]
@thomasdavis Yes, I think so. I don't have a npm account. I can set one up.

**Comment by thomasdavis** [comment]
Awesome, I've invited you to repo. 

Once I have your npm account, will add you.

Then you can just bump the version of package.json and deploy new changes.

**Comment by montdidier** [comment]
@thomasdavis I have signed up at npmjs with the same username as here.

**Comment by thomasdavis** [comment]
Awesome, I've invited you, welcome =D 

Merge your request, bump the version and then `npm publish` from the command line

**Comment by montdidier** [comment]
@thomasdavis do you have an opinion on this PR requiring node 10?

**Comment by thomasdavis** [comment]
@montdidier Nope, I think you are fine to merge.

**Pull request merged**
